---
name: Lint Code Base

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4.2.2
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_DOCKERFILE: false
          VALIDATE_JSON: false
          VALIDATE_BASH: false
          VALIDATE_BASH_EXEC: false